name: Release binaries

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  release-orbit:
    name: Release Orbit (${{ matrix.goos }}/${{ matrix.goarch }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v5
      - name: Set APP_VERSION env
        run: echo APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev) >> ${GITHUB_ENV}
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          binary_name: orbit
          project_path: ./cmd/orbit
          ldflags: "-X 'main.version=${{ env.APP_VERSION }}'"
          extra_files: LICENSE README.md

  release-apsis:
    name: Release Apsis (${{ matrix.goos }}/${{ matrix.goarch }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v5
      - name: Set APP_VERSION env
        run: echo APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev) >> ${GITHUB_ENV}
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          binary_name: apsis
          project_path: ./cmd/apsis
          ldflags: "-X 'main.version=${{ env.APP_VERSION }}'"
